// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: coffee_timer

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Arc1 = NULL;
lv_obj_t * ui_LowBattery = NULL;
lv_obj_t * ui_LowBatteryTip = NULL;
lv_obj_t * ui_LowBatteryVoltage = NULL;
lv_obj_t * ui_Countdown = NULL;
lv_obj_t * ui_UnitMarker = NULL;
lv_obj_t * ui_BankLabel = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    // Set explicitly rather than left to the theme: flow mode inverts the
    // panel, so both backgrounds have to be ours to put back.
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(SCREEN_BG_COLOR), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc1, 225);
    lv_obj_set_height(ui_Arc1, 225);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_arc_set_value(ui_Arc1, 100);
    lv_obj_set_style_arc_width(ui_Arc1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    // Explicit rather than the theme's, for the same reason as the screen's
    // background: flow mode swaps it for a light one and has to swap it back.
    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(ARC_TRACK_COLOR), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(ARC_COLOR_FULL), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // The knob tracks the indicator colour, so the leading dot doesn't sit
    // there in the theme's blue while the arc shades green to red.
    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(ARC_COLOR_FULL), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Arc1, lv_color_hex(0x5D5D5D), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Arc1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Arc1, 3, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Arc1, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    // Low-battery warning: an empty battery outline, drawn rather than taken
    // from a font so its size doesn't depend on which montserrat sizes the
    // LVGL build happens to enable. Hidden unless the charge is actually low.
    ui_LowBattery = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_LowBattery, 42);
    lv_obj_set_height(ui_LowBattery, 20);
    lv_obj_set_x(ui_LowBattery, -3);
    lv_obj_set_y(ui_LowBattery, 78);
    lv_obj_set_align(ui_LowBattery, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LowBattery, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_flag(ui_LowBattery, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_bg_opa(ui_LowBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LowBattery, lv_color_hex(LOW_BATTERY_COLOR), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LowBattery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LowBattery, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LowBattery, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_LowBattery, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // A sibling rather than a child: children are clipped to their parent, so
    // a terminal hung off the body's right edge would be drawn inside it.
    // x = 21 puts it just past the body, keeping the pair centred as a whole.
    ui_LowBatteryTip = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_LowBatteryTip, 4);
    lv_obj_set_height(ui_LowBatteryTip, 7);
    lv_obj_set_align(ui_LowBatteryTip, LV_ALIGN_CENTER);
    lv_obj_set_x(ui_LowBatteryTip, 21);
    lv_obj_set_y(ui_LowBatteryTip, 78);
    lv_obj_add_flag(ui_LowBatteryTip, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_LowBatteryTip, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_color(ui_LowBatteryTip, lv_color_hex(LOW_BATTERY_COLOR), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LowBatteryTip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LowBatteryTip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_LowBatteryTip, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // The measured pack voltage, printed inside the outline. It is there to be
    // read against a multimeter when calibrating the divider and ADC, so it
    // shows what the firmware actually measured rather than a derived figure.
    // A child of the body, so hiding the body hides this too.
    ui_LowBatteryVoltage = lv_label_create(ui_LowBattery);
    lv_obj_set_width(ui_LowBatteryVoltage, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LowBatteryVoltage, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_LowBatteryVoltage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LowBatteryVoltage, "0.00");
    lv_obj_set_style_text_color(ui_LowBatteryVoltage, lv_color_hex(LOW_BATTERY_COLOR), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LowBatteryVoltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LowBatteryVoltage, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Countdown = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Countdown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Countdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Countdown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Countdown, "00:00");
    lv_obj_set_style_text_font(ui_Countdown, &ui_font_Countdown_54, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Which two fields the countdown is showing. Past an hour MM:SS runs out of
    // digits and the label switches to HH:MM, which is indistinguishable from
    // the other without something saying so. In montserrat rather than the
    // countdown face, which is subset to digits and a colon.
    ui_UnitMarker = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_UnitMarker, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_UnitMarker, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_UnitMarker, LV_ALIGN_CENTER);
    lv_obj_set_y(ui_UnitMarker, 40);
    lv_label_set_text(ui_UnitMarker, "h:m");
    lv_obj_add_flag(ui_UnitMarker, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_text_color(ui_UnitMarker, lv_color_hex(COUNTDOWN_COLOR), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UnitMarker, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UnitMarker, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    // How much break the bank holds, shown above the flow work counter while a
    // stint runs. Above rather than below because the unit marker already owns
    // the space underneath.
    ui_BankLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_BankLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_BankLabel, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_BankLabel, LV_ALIGN_CENTER);
    lv_obj_set_y(ui_BankLabel, -42);
    lv_label_set_text(ui_BankLabel, "BANK 0:00");
    lv_obj_add_flag(ui_BankLabel, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_text_color(ui_BankLabel, lv_color_hex(COUNTDOWN_COLOR), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BankLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BankLabel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Arc1 = NULL;
    ui_LowBattery = NULL;
    ui_LowBatteryTip = NULL;
    ui_LowBatteryVoltage = NULL;
    ui_Countdown = NULL;
    ui_UnitMarker = NULL;
    ui_BankLabel = NULL;

}
